# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
use_frameworks!

target 'shaker' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for Shaker
  # pod 'TwitterKit'
  # pod 'Firebase/Analytics'
  # pod 'Google-Mobile-Ads-SDK'

  # pod 'FBSDKCoreKit'
  # pod 'FBSDKLoginKit'
  # pod 'FBSDKShareKit'
  # pod 'FBSDKMessengerShareKit'

end
